### ISSUE TITLE
Bugs occurred in other datasets

### ISSUE THREAD

**Issue by Cloudcatcher888** [HaojiHu/Sets2Sets#2]
I get a bug in T-mall datasets called:
```
(base) wzk@ddst:~/work/Sets2Sets$ python Sets2Sets.py ./data/alibaba_history.csv ./data/alibaba_future.csv 1 2 1
start dictionary generation...
{'MATERIAL_NUMBER': 9531}
# dimensions of final vector: 9531 | 2962
finish dictionary generation*****
num of vectors having entries more than 1: 16462
num of vectors having entries more than 1: 15275
Traceback (most recent call last):
  File "Sets2Sets.py", line 990, in <module>
    main(sys.argv)
  File "Sets2Sets.py", line 955, in main
    codes_freq = get_codes_frequency_no_vector(data_chunk[past_chunk],input_size,data_chunk[future_chunk].keys())
  File "Sets2Sets.py", line 935, in get_codes_frequency_no_vector
    for idx in X[pid]:
KeyError: '371250'
```
Have anyone met this before? I'd be really appreciated if anyone can help.

**Comment by HaojiHu** [comment]
The variable pid goes out of the bound of X. Try to make sure there is a pid 371250 in the data_chunk[past_chunk]. I had some preprocess to make sure the keys in data_chunk[future_chunk].keys() are contained in data_chunk[past_chunk].keys(). Thanks for reporting this. I will try to fix it later.
